#!/bin/bash
# Build Script Sync Launcher — generated by /build_script
# Re-run this script anytime to restart the sync daemon.
node ~/.claude/plugins/local/build_script/tools/sync-gdoc.js \
  --doc-id 12Oj8nOTk_Mdn7KnV5ufIcrnHK_NgYcDHNwgwtdQPrYc \
  --project-dir /Users/stefanocasafranca/code/casualLens \
  --hmac-secret-path ~/.config/build_script/hmac_secret \
  --daemonize

# Show live daemon logs so you can see what's happening
# Ctrl+C stops watching — the daemon keeps running in the background
LOG=/Users/stefanocasafranca/code/casualLens/.build_script/daemon.log
echo ""
echo "  ─────────────────────────────────────────────────────"
echo "  Live daemon log  (Ctrl+C stops watching — daemon keeps running)"
echo "  ─────────────────────────────────────────────────────"
echo ""
tail -f "$LOG"
